version: '3.7'
services:
    zookeeper:
      image: wurstmeister/zookeeper
      container_name: zookeeper_no_spring
      ports:
        - 2181:2181

    kafka:
      image: wurstmeister/kafka
      container_name: kafka_no_spring
      ports:
        - 9092:9092
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPIC: "Topic_odometer:1:3, Topic_statistic:1:3"